import type { GlobalThemeOverrides } from 'naive-ui'

export function createNaiveThemeOverrides(): GlobalThemeOverrides {
  return {
    common: {
      primaryColor: '#07c160',
      primaryColorHover: '#06ad56',
      primaryColorPressed: '#059a4c',
      primaryColorSuppl: '#06ad56',
      infoColor: '#10aeff',
      successColor: '#07c160',
      warningColor: '#fa9d3b',
      errorColor: '#fa5151',
      bodyColor: '#ededed',
      cardColor: '#ffffff',
      modalColor: '#ffffff',
      popoverColor: '#ffffff',
      inputColor: '#f7f7f7',
      tableColor: 'transparent',
      tableHeaderColor: '#f7f7f7',
      textColorBase: '#191919',
      textColor1: '#191919',
      textColor2: '#595959',
      textColor3: '#b2b2b2',
      borderColor: '#e5e5e5',
      dividerColor: '#e5e5e5',
      borderRadius: '8px',
      borderRadiusSmall: '6px',
      heightSmall: '32px',
      heightMedium: '38px',
      heightLarge: '42px',
      fontFamily: 'Inter, "Microsoft YaHei", "PingFang SC", ui-sans-serif, system-ui, sans-serif',
      fontFamilyMono: '"Cascadia Mono", "SFMono-Regular", Consolas, monospace',
      fontWeight: '400',
      fontWeightStrong: '600',
      boxShadow1: '0 1px 3px rgba(0, 0, 0, 0.04)',
      boxShadow2: '0 4px 16px rgba(0, 0, 0, 0.08)',
      boxShadow3: '0 8px 24px rgba(0, 0, 0, 0.12)',
    },
    Button: {
      heightSmall: '32px',
      heightMedium: '38px',
      heightLarge: '42px',
      borderRadiusSmall: '8px',
      borderRadiusMedium: '8px',
      borderRadiusLarge: '8px',
      fontSizeSmall: '13px',
      fontSizeMedium: '14px',
      fontSizeLarge: '15px',
      fontWeight: '600',
    },
    Input: {
      heightSmall: '32px',
      heightMedium: '38px',
      heightLarge: '42px',
      borderRadius: '8px',
    },
    Card: {
      borderRadius: '10px',
      titleFontWeight: '600',
      boxShadow: '0 1px 3px rgba(0, 0, 0, 0.04)',
    },
    Tabs: {
      tabColorSegment: '#f2f2f2',
      tabBorderRadius: '8px',
      tabFontWeightActive: '600',
    },
    DataTable: {
      borderColor: '#e5e5e5',
      thColor: '#f7f7f7',
      thColorHover: '#f2f2f2',
      tdColorHover: '#f7f7f7',
    },
    Dialog: {
      borderRadius: '12px',
    },
    Modal: {
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.12)',
    },
    Switch: {
      railColorActive: '#07c160',
      boxShadowFocus: '0 0 0 3px rgba(7, 193, 96, 0.16)',
    },
  }
}
